### ISSUE TITLE
DLL Files missing

### ISSUE THREAD

**Issue by TrYkeRm4N** [bijanbina/SamSignRem#1]
Hi!

First of all, thanks for your time and patience.

I check your blog:
https://bijan.binaee.com/2024/01/how-to-downgrade-samsung-sw-rev-check-fail/

Which brings me here.

I try to download the "required tool" SignRemover.exe, but it keeps crashing asking for some DLLs.

I'm trying to downgrade a Samsung S9 from Android 10 to 9, getting the SW REV. CHECK FAIL error message.

Could I ask for help? Lz4.exe works fine.

Thanks again Bijan!

**Comment by bijanbina** [comment]
Can you say what dll file, I can add those here and u test and if it works fine then I'll add it to the release files

**Comment by TrYkeRm4N** [comment]
libstdc++-6.dll
libgcc_s_seh-1.dll
libwinpthread-1.dll

Thanks for your fast reply!

What is the job for simg2img.exe? I open it and only said:
Using STDIN as input
Using STDOUT as output

**Comment by bijanbina** [comment]
Cant upload here, updated the release file. regarding functionality plz read src code
https://github.com/bijanbina/SamSignRem/releases/tag/v1.0

**Comment by TrYkeRm4N** [comment]
It works now, but when I downgrade I keep getting some errors and LTE doesn't work.

I return to Android 10, it works fine now

Thanks for your kind reply friend.

Cheers!
